/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PfmpPeriodsRouteImport } from './routes/pfmp-periods'
import { Route as MyStudentsRouteImport } from './routes/my-students'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as VisitsNewRouteImport } from './routes/visits.new'
import { Route as VisitsIdRouteImport } from './routes/visits.$id'
import { Route as SuperadminEstablishmentsRouteImport } from './routes/superadmin.establishments'
import { Route as SuperadminAiRouteImport } from './routes/superadmin.ai'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as PlacementsIdRouteImport } from './routes/placements.$id'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PfmpPeriodsRoute = PfmpPeriodsRouteImport.update({
  id: '/pfmp-periods',
  path: '/pfmp-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStudentsRoute = MyStudentsRouteImport.update({
  id: '/my-students',
  path: '/my-students',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const VisitsNewRoute = VisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIdRoute = VisitsIdRouteImport.update({
  id: '/visits/$id',
  path: '/visits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminEstablishmentsRoute =
  SuperadminEstablishmentsRouteImport.update({
    id: '/establishments',
    path: '/establishments',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminAiRoute = SuperadminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SuperadminRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const PlacementsIdRoute = PlacementsIdRouteImport.update({
  id: '/placements/$id',
  path: '/placements/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/my-students': typeof MyStudentsRoute
  '/pfmp-periods': typeof PfmpPeriodsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/teachers': typeof TeachersRoute
  '/placements/$id': typeof PlacementsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/superadmin/ai': typeof SuperadminAiRoute
  '/superadmin/establishments': typeof SuperadminEstablishmentsRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/students/': typeof StudentsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/my-students': typeof MyStudentsRoute
  '/pfmp-periods': typeof PfmpPeriodsRoute
  '/settings': typeof SettingsRoute
  '/teachers': typeof TeachersRoute
  '/placements/$id': typeof PlacementsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/superadmin/ai': typeof SuperadminAiRoute
  '/superadmin/establishments': typeof SuperadminEstablishmentsRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/students': typeof StudentsIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/companies': typeof CompaniesRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/exports': typeof ExportsRoute
  '/login': typeof LoginRoute
  '/my-students': typeof MyStudentsRoute
  '/pfmp-periods': typeof PfmpPeriodsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/teachers': typeof TeachersRoute
  '/placements/$id': typeof PlacementsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/superadmin/ai': typeof SuperadminAiRoute
  '/superadmin/establishments': typeof SuperadminEstablishmentsRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/students/': typeof StudentsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/assignments'
    | '/classes'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/exports'
    | '/login'
    | '/my-students'
    | '/pfmp-periods'
    | '/settings'
    | '/students'
    | '/superadmin'
    | '/teachers'
    | '/placements/$id'
    | '/students/$id'
    | '/superadmin/ai'
    | '/superadmin/establishments'
    | '/visits/$id'
    | '/visits/new'
    | '/students/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/assignments'
    | '/classes'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/exports'
    | '/login'
    | '/my-students'
    | '/pfmp-periods'
    | '/settings'
    | '/teachers'
    | '/placements/$id'
    | '/students/$id'
    | '/superadmin/ai'
    | '/superadmin/establishments'
    | '/visits/$id'
    | '/visits/new'
    | '/students'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/alerts'
    | '/assignments'
    | '/classes'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/exports'
    | '/login'
    | '/my-students'
    | '/pfmp-periods'
    | '/settings'
    | '/students'
    | '/superadmin'
    | '/teachers'
    | '/placements/$id'
    | '/students/$id'
    | '/superadmin/ai'
    | '/superadmin/establishments'
    | '/visits/$id'
    | '/visits/new'
    | '/students/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  CompaniesRoute: typeof CompaniesRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ExportsRoute: typeof ExportsRoute
  LoginRoute: typeof LoginRoute
  MyStudentsRoute: typeof MyStudentsRoute
  PfmpPeriodsRoute: typeof PfmpPeriodsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TeachersRoute: typeof TeachersRoute
  PlacementsIdRoute: typeof PlacementsIdRoute
  VisitsIdRoute: typeof VisitsIdRoute
  VisitsNewRoute: typeof VisitsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfmp-periods': {
      id: '/pfmp-periods'
      path: '/pfmp-periods'
      fullPath: '/pfmp-periods'
      preLoaderRoute: typeof PfmpPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-students': {
      id: '/my-students'
      path: '/my-students'
      fullPath: '/my-students'
      preLoaderRoute: typeof MyStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/visits/new': {
      id: '/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof VisitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/$id': {
      id: '/visits/$id'
      path: '/visits/$id'
      fullPath: '/visits/$id'
      preLoaderRoute: typeof VisitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/establishments': {
      id: '/superadmin/establishments'
      path: '/establishments'
      fullPath: '/superadmin/establishments'
      preLoaderRoute: typeof SuperadminEstablishmentsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/ai': {
      id: '/superadmin/ai'
      path: '/ai'
      fullPath: '/superadmin/ai'
      preLoaderRoute: typeof SuperadminAiRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/placements/$id': {
      id: '/placements/$id'
      path: '/placements/$id'
      fullPath: '/placements/$id'
      preLoaderRoute: typeof PlacementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminAiRoute: typeof SuperadminAiRoute
  SuperadminEstablishmentsRoute: typeof SuperadminEstablishmentsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAiRoute: SuperadminAiRoute,
  SuperadminEstablishmentsRoute: SuperadminEstablishmentsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  CompaniesRoute: CompaniesRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ExportsRoute: ExportsRoute,
  LoginRoute: LoginRoute,
  MyStudentsRoute: MyStudentsRoute,
  PfmpPeriodsRoute: PfmpPeriodsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  TeachersRoute: TeachersRoute,
  PlacementsIdRoute: PlacementsIdRoute,
  VisitsIdRoute: VisitsIdRoute,
  VisitsNewRoute: VisitsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
